import type { DashboardData } from "./types";

export const mockData: DashboardData = {
  generatedAt: "2026-07-27 09:00 KST",
  signalsDate: "2026-07-27",
  summary: {
    nav: 118420,
    cash: 32110,
    nPositions: 7,
    candidatesPassed: 4,
    regime: "Confirmed Uptrend",
    regimeStatus: "good",
    maxExposurePct: 100,
    newEntriesPerWeek: 3,
    nRunners: 1,
    nPyramided: 2,
    nTrimmed: 1,
  },
  regimeHistory: [
    "Correction", "Correction", "Rally Attempt", "Rally Attempt", "Uptrend Resumed",
    "Uptrend Resumed", "Confirmed Uptrend", "Confirmed Uptrend", "Confirmed Uptrend",
    "Uptrend Under Pressure", "Confirmed Uptrend", "Confirmed Uptrend", "Confirmed Uptrend",
    "Confirmed Uptrend", "Confirmed Uptrend", "Confirmed Uptrend", "Confirmed Uptrend",
    "Uptrend Under Pressure", "Confirmed Uptrend", "Confirmed Uptrend", "Confirmed Uptrend",
    "Confirmed Uptrend", "Confirmed Uptrend", "Confirmed Uptrend", "Confirmed Uptrend",
    "Confirmed Uptrend", "Confirmed Uptrend", "Confirmed Uptrend", "Confirmed Uptrend",
    "Confirmed Uptrend",
  ].map((regime, i) => ({
    date: `2026-06-${String(i + 1).padStart(2, "0")}`,
    regime: regime as DashboardData["regimeHistory"][number]["regime"],
  })),
  navHistory: Array.from({ length: 24 }, (_, i) => ({
    date: `2026-06-${String(i * 2 + 1).padStart(2, "0")}`,
    nav: 100000 + i * 800 + (i % 3 === 0 ? -1500 : 0),
  })),
  backtest: {
    startDate: "2021-01-04",
    endDate: "2026-07-24",
    totalReturnPct: 135.0,
    mddPct: -18.4,
    nTrades: 214,
    winRatePct: 47,
    benchmarks: [
      { label: "SPY", returnPct: 78.2, excessPct: 56.8 },
      { label: "QQQ", returnPct: 102.6, excessPct: 32.4 },
    ],
  },
  breadth: {
    above50emaPct: 61.4,
    netNewHighs: 38,
    universeCount: 487,
  },
  sentiment: {
    vix: 14.2,
    vixLabel: "낮음",
    concentrationGap: -3.1,
    concentrationLabel: "로테이션 진행",
    breadthStrongPct: 22.5,
    breadthStrongLabel: "보통",
    fearGreedScore: 58,
    fearGreedLabel: "탐욕",
    cnnFearGreedScore: 61,
    cnnFearGreedLabel: "탐욕",
  },
  distributionRally: {
    spxDistributionDays: 3,
    spxRallyDays: 5,
    ndxDistributionDays: 2,
    ndxRallyDays: 6,
  },
  newHighsLows: [
    { kind: "신고가", ticker: "NVDA", sector: "Technology", industry: "Semiconductors", close: 142.31, rsRating: 97, extensionPct200sma: 42 },
    { kind: "신고가", ticker: "PLTR", sector: "Technology", industry: "Software", close: 38.92, rsRating: 95, extensionPct200sma: 68 },
    { kind: "신저가", ticker: "SMCI", sector: "Technology", industry: "Hardware", close: 21.04, rsRating: 12, extensionPct200sma: -31 },
  ],
  gateFunnel: [
    { key: "G0", label: "G0", count: 487, total: 500 },
    { key: "G1", label: "G1", count: 210, total: 500 },
    { key: "G2", label: "G2", count: 96, total: 500 },
    { key: "G3", label: "G3", count: 41, total: 500 },
    { key: "G4", label: "G4", count: 18, total: 500 },
    { key: "passed", label: "최종 통과", count: 4, total: 500 },
  ],
  candidates: [
    {
      ticker: "NVDA", sector: "Technology", industry: "Semiconductors", close: 142.31, marketCap: 3.5e12,
      score: 94.2, mtrState: 7, mtrAccelerating: true, adRating: "A", rvol: 1.62, baseLabel: "2nd",
      patternName: "VCP", gates: { G0: true, G1: true, G2: true, G3: true, G4: true }, passed: true,
      newHigh52w: true, high52w: 142.31,
    },
    {
      ticker: "PLTR", sector: "Technology", industry: "Software", close: 38.92, marketCap: 8.4e10,
      score: 91.8, mtrState: 7, mtrAccelerating: true, adRating: "A", rvol: 1.41, baseLabel: "1st",
      patternName: "Ascending Base", gates: { G0: true, G1: true, G2: true, G3: true, G4: true }, passed: true,
      newHigh52w: true, high52w: 38.92,
    },
    {
      ticker: "AVGO", sector: "Technology", industry: "Semiconductors", close: 218.55, marketCap: 1.02e12,
      score: 88.1, mtrState: 3, mtrAccelerating: false, adRating: "B", rvol: 1.05, baseLabel: "3rd",
      patternName: null, gates: { G0: true, G1: true, G2: true, G3: true, G4: false }, passed: false,
      newHigh52w: false, high52w: 235.1,
    },
  ],
  sectorBreakdown: [
    { sector: "Technology", industry: "Semiconductors", count: 14, avgRs: 88.2, avgScore: 79.4, leading: true, passed: 3 },
    { sector: "Technology", industry: "Software", count: 22, avgRs: 81.5, avgScore: 74.1, leading: true, passed: 2 },
    { sector: "Healthcare", industry: "Biotechnology", count: 9, avgRs: 64.3, avgScore: 58.9, leading: false, passed: 0 },
  ],
  indexRs: [
    { label: "S&P500", rs: 68.4 },
    { label: "나스닥100", rs: 74.1 },
    { label: "다우존스", rs: 52.7 },
  ],
  holdings: [
    { ticker: "NVDA", entryPx: 118.2, lastClose: 142.31, gainPct: 20.4, currentStopPct: -8, isRunner: true, pyramided: true, climaxTrimmed: false },
    { ticker: "AAPL", entryPx: 224.1, lastClose: 231.5, gainPct: 3.3, currentStopPct: -8, isRunner: false, pyramided: false, climaxTrimmed: false },
    { ticker: "MSTR", entryPx: 402.0, lastClose: 512.4, gainPct: 27.5, currentStopPct: -6, isRunner: false, pyramided: true, climaxTrimmed: true },
  ],
  recentTrades: [
    { ticker: "AMD", entryDate: "2026-06-02", exitDate: "2026-07-11", entryPx: 132.4, exitPx: 118.9, pnlPct: -10.2, reason: "stop" },
    { ticker: "CRWD", entryDate: "2026-05-14", exitDate: "2026-07-08", entryPx: 289.0, exitPx: 341.2, pnlPct: 18.1, reason: "climax_trim" },
    { ticker: "SHOP", entryDate: "2026-04-22", exitDate: "2026-06-30", entryPx: 78.5, exitPx: 71.2, pnlPct: -9.3, reason: "sell_below_50ma" },
  ],
  alphaDecay: {
    reliable: true,
    overallWinRate: 47,
    recentWinRate: 43,
    decayPp: -4,
    status: "주의",
    nOverall: 214,
    nRecent: 22,
  },
  set2: {
    nav: 9998.75,
    cash: 7500,
    nPositions: 1,
    navHistory: [{ date: "2026-08-05", nav: 9998.75 }],
    holdings: [
      { ticker: "NTAP", entryPx: 190.46, lastClose: 190.46, gainPct: 0, currentStopPct: -8, trimStage: 0 },
    ],
    recentTrades: [],
    backtest: {
      startDate: "2021-07-28",
      endDate: "2026-07-28",
      totalReturnPct: 107.3,
      mddPct: -29.8,
      nTrades: 74,
      winRatePct: 57,
      benchmarks: [
        { label: "SPY", returnPct: 80.6, excessPct: 26.6 },
        { label: "QQQ", returnPct: 90.3, excessPct: 17.0 },
      ],
      exitReasons: [
        { reason: "stop", count: 32, avgPnlPct: -9.7 },
        { reason: "stop_locked8", count: 7, avgPnlPct: 5.6 },
        { reason: "trim1_24pct", count: 16, avgPnlPct: 27.0 },
        { reason: "trim2_50pct", count: 11, avgPnlPct: 53.4 },
        { reason: "final_100", count: 8, avgPnlPct: 101.7 },
      ],
    },
  },
};
